### ISSUE TITLE
 java.lang.SecurityException: Need BLUETOOTH permission

### ISSUE THREAD

**Issue by james04gr** [twilio/audioswitch#106]
**Describe the bug**
In my android application i have used the audioSwitch dependency. While i have tested my app on Android 10 && Android 11 devices when i run the application in an Android 12 device i get a SecurityException like below

`java.lang.SecurityException: Need BLUETOOTH permission`
 when i try to run the audioSwitch.start

After a little research that i have made, i saw that Android 12 has some restrictions in the Bluetooth functionality. Specifically, 
`The BLUETOOTH_ADVERTISE, BLUETOOTH_CONNECT, and BLUETOOTH_SCAN permissions are runtime permissions. `

So i guess you need to update your code as soon as Android 12 comes to a Release mode

**Comment by 4brunu** [comment]
Did you tried the last version 1.1.3?

**Comment by james04gr** [comment]
Well, i updated the dependency as you suggested and everything works fine. Thank you

**Comment by 4brunu** [comment]
Could you please close this issue? 🙂
