### ISSUE TITLE
External HMD is not playing Audio 

### ISSUE THREAD

**Issue by noumanshah115** [twilio/audioswitch#111]
AudioSwitch is not picking WiredHeadset as avilableDevice 
we have a device that has external speaker and display and work good when there is no twilio session
For video calling as we start the twilio session The sound is automatically route to speaker of phone Though the hmd is connected 
when i call audioSwitch.start { _, _ -> } 
The device doe not pick WiredHeadset and the show the only avilable devices as "Speakerphone" and "Earpiece"

**Comment by afalls-twilio** [comment]
@noumanshah115 What device is it?

**Comment by noumanshah115** [comment]
@afalls-twilio  it is VR hardware(contain's mic and speaker) connected through external USB C cable

**Comment by afalls-twilio** [comment]
@noumanshah115 If a custom audio device is being used, then I would recommend creating a custom audio source for the item or extending audioswitch (its open source), to also support the custom VR Hardware.
