### ISSUE TITLE
After selecting a bluetooth device, the AudioDeviceChangeListener is called first with selectedAudioDevice = BluetoothHeadset (correct) and then with selectedAudioDevice = Earpiece(without user selection) a few seconds later

### ISSUE THREAD

**Issue by akardas16** [twilio/audioswitch#119]
Hi, I saw that you discussed this issue but I can still reproduce this bug every time. even though selected device routes to Earpiece, I still receive call audio from Bluetooth. 

Also on android 12 sometimes we receive voice over bluetooth, other times we receive voice from speaker or Earpiece while we already connected to a bluetooth device

**Comment by pegurin** [comment]
Same issue here with Samsung A72, Android 12 and Galaxy Buds Live as bluetooth device.

**Comment by robholmes** [comment]
I see exactly the same issue of switching to BT headset and hearing the call audio, but then a few seconds later being switched back to Earpiece, even though the call audio is still routed over BT.

version: `com.twilio:audioswitch:1.1.4`
device: Samsung Galaxy Tab Active 2
android: 9

**Comment by afalls-twilio** [comment]
Thank you @robholmes for submitting a fix for this issue its greatly appreciated. It has been tested and your MR has been merged.
