### ISSUE TITLE
Cannot use bluetooth headsets when targetSdkVersion < 31 and Build.VERSION >= 31

### ISSUE THREAD

**Issue by nredaatepic** [twilio/audioswitch#127]
**Describe the bug**
In adding support for API level 31, commit [07dfe6fd3052ec90346b5700ad08bcc5f5c92e7d](https://github.com/twilio/audioswitch/commit/07dfe6fd3052ec90346b5700ad08bcc5f5c92e7d#diff-a2712c763fb4ee092a7266f440ece9cbe3e09165f322591d7214197aacdba61c) introduced logic in BluetoothHeadsetManager.kt to determine a strategy for checking against the new bluetooth permissions. 

However, I believe this logic is incorrect - it is checking Build.VERSION, but internally (at least in [BluetoothHeadset.java](https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-31/blob/2c56b25f619575bea12f9c5520ed2259620084ac/android/bluetooth/BluetoothHeadset.java#L376)) android checks for targetSdkVersion.

From what I can tell, the BLUETOOTH and BLUETOOTH_CONNECT permissions are mutually exclusive (requesting one denies the other), so it's impossible to pass both of these checks when targetSdkVersion < 31 (fails in BluetoothHeadset.java) and Build.VERSION >= 31 (fails in BluetoothHeadsetManager.kt)

**AudioSwitch Version**
- Version: 1.1.5

**Comment by davidliu** [comment]
As a workaround, you can request the BLUETOOTH permission without specifying a `maxSdkVersion`, and it should pass since the BLUETOOTH permission can't normally be denied, and will be granted if the targetSdkVersion is <31.

**Comment by afalls-twilio** [comment]
Thank you @davidliu @nredaatepic for the fix. We would like to offer you something for your contribution... please reach out to afalls@twilio.com

**Comment by kanclalg** [comment]
@afalls-twilio when are you planning to release this fix?
