### ISSUE TITLE
Permission checks causing crashes, CircleCI failure on latest distrution attempt.

### ISSUE THREAD

**Issue by Orbyt** [twilio/audioswitch#133]
**Describe the bug**
Hello, #129 was merged several months ago but was not released. It seems the CircleCI pipeline associated with this project is failing, thus preventing the fixes in that PR from being released. Are there any plans of resolving that issue? 

Note that using `1.1.5-SNAPSHOT` does not work as the changes introduced in that PR (#129) are not included with that artifact.

Additionally, I'd like to ask about the permissions requirements noted in the [Permissions](https://github.com/twilio/audioswitch#permissions) section. That section notes that `BLUETOOTH_CONNECT` must be requested by users of this SDK by adding it to an AndroidManifest, yet the SDK seems to have that permission already declared ([AndroidManifest.xml](https://github.com/twilio/audioswitch/blob/master/audioswitch/src/main/AndroidManifest.xml)). Is that permission not merged when manifests are merged?

Finally, it seems runtime permission are required for `BLUETOOTH_CONNECT`. Why are those runtime permission not handled by this library, considering that the library requires that permission? Are those runtime checks going to be added in the future?

Thank you!

**Comment by ocarevs** [comment]
Hi @Orbyt CircleCI pipeline and permission check crash have been fixed as version 1.1.7. 
Regarding `BLUETOOTH_CONNECT` permission, manifests are merged. what permission documentation is trying to say is that this permission has to be granted/handled by the user as of Android 12 in order for bluetooth capabilities to work while using this library.
As of now there is no plan to handle `BLUETOOTH_CONNECT` permission by the library.
