### ISSUE TITLE
Play different audio on 2 outputs at the same time

### ISSUE THREAD

**Issue by michaelonz** [twilio/audioswitch#146]
Hi - I want to be able to play audio out the headphone 3.5mm port and at the same time play a DIFFERENT audio out the front speaker on the phone - is it possible to achieve this using this library?  (device is android 11 currently but if i needed a new os i would consider getting a newer device).

I have looked at various api calls but at this stage I am not even sure if android can have this capabilty - your audio expert view on if this is possible would be appreciated.

**Comment by afalls-twilio** [comment]
This library currently does not support that feature. Other members have asked about it and it is possible with modifications to this library but at this time, adding support is not on the roadmap.

**Comment by michaelonz** [comment]
Do you know of any fork that shows an example of how this is done?  Or any other code that might point me in the right direction please?
