### ISSUE TITLE
Select for input device A for output device B

### ISSUE THREAD

**Issue by Yuriy29** [twilio/audioswitch#151]
Implement the possibility to set different source for input and output, for example for input Bluetooth device for output phone microphone. Or it have already been implemented in the lib?

**Comment by afalls-twilio** [comment]
@Yuriy29 This feature is not supported by audio switch, and supporting it would require a significant redesign of the library. Feel free to attempt to do it yourself though, It would entail using the [androidx.mediarouter](https://developer.android.com/reference/androidx/mediarouter/media/package-summary) APIs and more complicated Bluetooth APIs.
