### ISSUE TITLE
Apps targeting Android 14 lose input audio when phone is locked or app is in background

### ISSUE THREAD

**Issue by AlanMTuring** [twilio/audioswitch#158]
**Describe the bug**
Our production app targets Android 14 and uses the AudioSwitch. When users are on Android 14 and either lock their screen or put our app in the background, they can hear audio come through but audio input no longer works.

I've also been able to reproduce on the [voice quickstart](https://github.com/twilio/voice-quickstart-android) by bumping the targetSdk to 34. Doing so required the following changes to the project:
- ` <uses-permission android:name="android.permission.FOREGROUND_SERVICE_PHONE_CALL"/>` to `connection_service/AndroidManifest.xml`
- `android:foregroundServiceType="phoneCall"` to IncomingCallNotificationService in `connection-service/AndroidManifest.xml`
- `super.onRequestPermissionsResult(requestCode, permissions, grantResults);` to `onRequestPermissionsResult(...)` in `VoiceActivity.java`

Similar to an [older issue](https://github.com/twilio/voice-quickstart-android/issues/460), but new for Android 14.

**To Reproduce**
1. Start a call
2. Confirm input/output audio works
3. Lock screen OR put app in background
4. Input audio no longer works

**Expected behavior**
Locking screen or putting app in background with the foreground service started should keep the input audio working

**Actual behavior**
Locking screen or putting app in background causes the input audio to stop working

**Application Logs**
- AudioSwitch with logging enabled set to true outputs no logs when locking the screen.

**AudioSwitch Version**
- Version: 1.1.8

**Android Device (please complete the following information):**
 - Device: Confirmed on Pixel 8 Pro, Pixel 7, Samsung S23
 - API Version: API 34

**Screenshots**
N/A

**Additional context**
N/A

**Comment by afalls-twilio** [comment]
@AlanMTuring This is probably due to the activity being backgrounded. What happens if instead of passing the activity context to the Voice.Connect, you passed the application context, this issue should not happen.

**Comment by AlanMTuring** [comment]
In our production app, we are already passing in the application context to the voice connect and into the AudioSwitch creation, and the problem is still there.

With the quickstart, I edited the code in `VoiceActivity.handleCallRequest()` so that `Voice.connect` takes in the application context and in `VoiceActivity.answer()` so that `activeCallinvite.accept()` also takes in the application context. After those changes, i was still able to reproduce the issue.

**Comment by afalls-twilio** [comment]
@AlanMTuring ok, My next question is are you integrating with the ConnectionService API? If not, you shouldn't be using the FOREGROUND_SERVICE_PHONE_CALL and instead should use FOREGROUND_SERVICE_MICROPHONE.. For more info look here..

`Continue microphone capture from the background, such as voice recorders or communication apps.`

https://developer.android.com/about/versions/14/changes/fgs-types-required#microphone

**Comment by tech-ajit-mob** [comment]
@AlanMTuring  are you facing the issue of auto-selected audio mode from Speaker/BT to earpiece mode after some time when the application is put in the background?

Interestingly, when I tried to switch the audio mode from the phone to the speaker or Bluetooth, it didn't work and the audio continued to come through the earpiece.

Current audio switch SDK version :
`  implementation 'com.twilio:audioswitch:1.2.0'`

Please help me.
