### ISSUE TITLE
Car play show wrong caller id and also audio doesn't end on call end, required to force close the app 

### ISSUE THREAD

**Issue by softsan** [twilio/audioswitch#161]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Github Issues](https://github.com/twilio/audioswitch/issues)
>  * [Changelog](https://github.com/twilio/audioswitch/blob/master/CHANGELOG.md)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

**Describe the bug**
In continuation of this [bug](https://github.com/twilio/audioswitch/issues/157) I found another issue related to car audio. I am using it with the voice sdk android for my voip calling app. When an incoming call came in, it shows binary number like 1000000 as caller id on car dashboard while on my mobile app it shows correct caller id. so my caller id is like` phone number - name` or some time `name - team name`(both strings). Also when call is ended from app it still ongoing on car bluetooth and it only ends when i force close the app. So any resolution on this?

**To Reproduce**

**Expected behavior**
It should end the call from car bluetooth without force closing app. Also it should show correct caller id instead of 100000 number.

**Actual behavior**
It shows wrong caller id with some binary number like 100000 and also call is not ended on car dashboard when ending from mobile app. 

**Application Logs**
- Logcat logs with [logging enabled](https://twilio.github.io/audioswitch/latest/audioswitch/com.twilio.audioswitch/-audio-switch/-audio-switch.html) and `AS/` logcat filter applied.

**AudioSwitch Version**
- Version:1.1.8

**Android Device (please complete the following information):**
 - Device:Car audio/play bluetooth 
 - API Version: 33/34

**Screenshots**
<img width="531" alt="car_bt" src="https://github.com/twilio/audioswitch/assets/7391319/eb059ec9-134e-4d86-9f43-fd2f97a205f1">

**Additional context**

**Comment by softsan** [comment]
Any updates on this? or workaround?

**Comment by ocarevs** [comment]
@softsan AudioSwitch currently does not support any custom bluetooth actions, we only trap connection and disconnection actions. At this point this is not on our timeline, but it's not to say that we could not add support for custom actions at later date.
