### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by Bayramito** [twilio/audioswitch#168]
I just checked this package and it is so helpful and powerful.

Would be great to have such thing in react native world. 

Especially when you wan't to have a custom solution for real time communications in react native, dealing with audio devices is a big task. And this package do have all the stuff that we need. 

In react native community almost there is no a perfect solution such as this package. 

Would be great to see this in react native, even for only Android side

**Comment by afalls-twilio** [comment]
@Bayramito We have no plans to make a React Native version on this project at this time but it is a component of our [React Native Voice SDK](https://github.com/twilio/twilio-voice-react-native), if that is of any interest to you.
