### ISSUE TITLE
Bluetooth Device Name may be null

### ISSUE THREAD

**Issue by cyodrew** [twilio/audioswitch#22]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Github Issues](https://github.com/twilio/audioswitch/issues)
>  * [Changelog](https://github.com/twilio/audioswitch/blob/master/CHANGELOG.md)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

**Describe the bug**
The `BluetoothDeviceWrapperImpl` gets the name of the Bluetooth device by pulling it from the Android `BluetoothDevice` class by calling its `getName()` method. However, this method can possibly return null, causing an `IllegalStateException` to be thrown and a crash in the app using the library.

**To Reproduce**
1. Inside `BluetoothDeviceWrapperImpl`, `device.name` is called
2. There are three places in the Java method `getName()` where a null String could be returned
3. Replicate this behavior with the debugger by modifying the `name` variable of the `getName()` method in the Android `BluetoothDevice` class to be null
4. `IllegalStateException` is thrown

**Expected behavior**
This field should be nullable or given a default name value if it cannot be found.

**Screenshots**

**Android Device (please complete the following information):**
 - Device: Pixel 3a
 - API Version: API 29

**Version**
- Version: 0.1.2

**Additional context**

**Comment by Alton09** [comment]
Hi @cyodrew . Thanks for filing this issue! We'll address this bug and respond here once it has been resolved.

**Comment by Alton09** [comment]
@cyodrew Resolved this issue in pr #23 and cut a new pre release `0.1.3`. Thanks again for reporting this issue!
