### ISSUE TITLE
About bluetooth device connection during a call

### ISSUE THREAD

**Issue by sdfadsfsdf** [twilio/audioswitch#26]
### Question

https://github.com/twilio/audioswitch

Imported the audio switch library.
However, there is no sound when Bluetooth is connected during a call.

```
 audioDeviceSelector.start { _: List<AudioDevice?>, selectedDevice: AudioDevice? ->
    Log.d("selectedDevice", selectedDevice.toString())
    Log.d("selectedDevice2",audioDeviceSelector.selectedAudioDevice.toString())
 }
```

```
2020-06-08 18:10:50.050 24865-24865/com.sansan.debug D/selectedDevice: Earpiece(name=Earpiece)
2020-06-08 18:10:50.050 24865-24865/com.sansan.debug D/selectedDevice2: Earpiece(name=Earpiece)
2020-06-08 18:10:59.114 24865-24865/com.sansan.debug D/selectedDevice: BluetoothHeadset(name=Daisuke AirPods)
2020-06-08 18:10:59.114 24865-24865/com.sansan.debug D/selectedDevice2: BluetoothHeadset(name=Daisuke AirPods)
```
After connecting to Bluetooth, I hear a sound when I make a call.

Voice Android SDK:5.2.0
OS Version:Android 10
Device Model:Galaxy S10

**Comment by Alton09** [comment]
Hi @sdfadsfsdf ! Thanks for reporting this issue. A bug fix for this issue is currently in development and a new release with the fix will be available soon. In the meantime, you can get around this issue by manually invoking `selectDevice()` and `activate()` as described in the [README](https://github.com/twilio/audioswitch#select-a-device).

**Comment by sdfadsfsdf** [comment]
I'm looking forward to seeing the update.

**Comment by Alton09** [comment]
Hi @sdfadsfsdf . A fix is out for this issue in the latest release, [0.1.4](https://github.com/twilio/audioswitch/releases/tag/0.1.4). Please let me know if the new release resolves this issue so I can close it. Thanks!

**Comment by sdfadsfsdf** [comment]
LGTM!
