### ISSUE TITLE
During call when switch over Speaker to Wired Headset echo and noise happening

### ISSUE THREAD

**Issue by Prasannakumarkannan** [twilio/audioswitch#30]

**Comment by aaalaniz** [comment]
Hey @Prasannakumarkannan 

Please follow the Troubleshooting Audio guide in our [Video Android Quickstart](https://github.com/twilio/video-quickstart-android#troubleshooting-audio). If you are still unable to resolve the echo issues, then please open an issue on the Video Android Quickstart project with the issue template filled out as best you can. Audioswitch does not manage or provide any echo cancellation facilities.

Thank you
