### ISSUE TITLE
Selecting and activating a device does not switch

### ISSUE THREAD

**Issue by aaalaniz** [twilio/audioswitch#31]
**Describe the bug**
Selecting a device and then calling `activate` does not always switch to the selected device. For example, if the user is using a bluetooth headset and then switches to earpiece, this transition may not always succeed.

**To Reproduce**
1. Select a bluetooth device
2. Call activate
3. Select earpiece
4. Call activate

**Expected behavior**
The library switches audio output to the earpiece.

**Actual behavior**
The audio output remains on bluetooth device.

**Android Device (please complete the following information):**
 - Device: OnePlus 6T
 - API Version: Android 10

**Version**
- Version: 0.4.0

**Additional context**
This bug was originally reported in #28

**Comment by Alton09** [comment]
Fixed as part of 0.2.0.
