### ISSUE TITLE
Apple AirPods do not show up as bluetooth device when connected

### ISSUE THREAD

**Issue by aaalaniz** [twilio/audioswitch#32]
**Describe the bug**
Apple AirPods do not show up in `availableDevices` when connected to an Android phone. (Apparently [they work with Android devices](https://www.macrumors.com/guide/airpods-android/)) 😄 

**To Reproduce**
1. Connect a pair of Airpods to Android devices
2. Start audio device selector
3. Query availableDevices

**Expected behavior**
Airpods should show up in the available devices.

**Actual behavior**
Airpods do not show up as an available devices

**Version**
- Version: 0.1.4

**Additional context**
Originally reported in #28

**Comment by Alton09** [comment]
I tested this on a Pixel 3 running AudioSwitch 0.1.4, and I was able to successfully connect a pair of Air Pods with audio output routing to it. I was also able to see the correct device name as shown in the following screenshots.

![Screenshot_20200618-154142](https://user-images.githubusercontent.com/2661383/85077624-f8b81d00-b17f-11ea-93c6-8576fc5cc913.png)

<img width="790" alt="Screen Shot 2020-06-18 at 3 44 44 PM" src="https://user-images.githubusercontent.com/2661383/85077635-fe156780-b17f-11ea-9163-375c7915f04a.png">

@aaalaniz Closing this issue for now. I'm thinking we should prioritize the [multiple bluetooth device support story](https://issues.corp.twilio.com/browse/AHOYAPPS-652) as the reported issues appear to be related to connecting multiple devices at once.

**Comment by alizeec** [comment]
Hey
What I said in the issue [#28](https://github.com/twilio/audioswitch/issues/28#event-3458899425) is not what is describe here.

It's possible to connect and see AirPods, but sometimes, the name displayed is the name of another bluetooth device, in this case my watch. But it's random, that's why you didn't had the issue @Alton09 

Can you please re-open the issue ?

**Comment by aaalaniz** [comment]
Hey @alizeec 

I think what are you describing relates to supporting multiple Bluetooth devices #15. I think the reason you occasionally don't see the AirPods is because the library will only add one Bluetooth device to the `availableDevices`. We have a story in our backlog to improve support for multiple bluetooth devices.

Thanks!

**Comment by alizeec** [comment]
Hey @aaalaniz 
If the library detects only my watch, how can the audio be properly routed to my AirPods ?

Thanks

**Comment by Alton09** [comment]
@alizeec Since the library currently only supports a single connected bluetooth device, you should get consistent behavior if you just connect just your AirPods. Please keep an eye out for #15 as we are planning to provide support for multiple bluetooth devices. Thanks!
