### ISSUE TITLE
Calling audioDeviceSelector.deactivate() doesn't transfer back the audio focus to the previous focus owner on pre Oreo devices

### ISSUE THREAD

**Issue by tejas-n** [twilio/audioswitch#38]
**Describe the bug**
Calling `audioDeviceSelector.deactivate()` doesn't transfer back the audio focus to the previous focus owner on pre Oreo devices

**To Reproduce**
1. Have an app 'A' request audio focus and play some media file.
2. Have another app 'B' using audioswitch library to call `audioDeviceSelector.start(..)` and `audioDeviceSelector.activate(..)`
3. The audio focus is transferred from app A to app B. 
4. Call `audioDeviceSelector.deactivate()` and `audioDeviceSelector.stop()` in app B.
5. The audio focus is not transferred back from app B to app A i.e. app A doesn't receive `AUDIOFOCUS_GAIN` in it's audio focus listener

**Expected behavior**
Previous audio focus owner should get back the focus

**Actual behavior**
Previous audio focus owner doesn't get back the focus

**Android Device (please complete the following information):**
 - Device: TCL Xess
 - API Version: API 22

**Additional context**
I think the issue arises due to these parts
https://github.com/twilio/audioswitch/blob/d2bf4340fb79f1d0fc600cd29bf9fd2c7d9c74c0/audioswitch/src/main/java/com/twilio/audioswitch/selection/AudioDeviceManager.kt#L61-L66
https://github.com/twilio/audioswitch/blob/d2bf4340fb79f1d0fc600cd29bf9fd2c7d9c74c0/audioswitch/src/main/java/com/twilio/audioswitch/selection/AudioDeviceManager.kt#L102-L104

The audio focus listener object which was used to request the audio focus isn't used when abandoning the focus

**Comment by tejas-n** [comment]
I've created a PR here https://github.com/twilio/audioswitch/pull/39. Can you have a look at it, please?

I'm not sure if you accept contributions or what your usual process is. I haven't incremented version as well since I wasn't sure. Feel free to give feedback or decline the PR if you don't accept contributions. Thanks.

**Comment by Alton09** [comment]
Closing as this issue has been fixed as part of #44 .

**Comment by aaalaniz** [comment]
Hey @tejas-n 

We recently put together a short [contributing guide](https://github.com/twilio/audioswitch#contributing). We noticed that your changes were merged in by @Alton09, but you do not show up on the contributors page. If you would like, do you mind submitting a PR that adds you to the [contributors](https://github.com/twilio/audioswitch/blob/master/CONTRIBUTORS.md) file? This way you will show up on the contributors page.

Again, this is totally optional. Thank you!

**Comment by tejas-n** [comment]
@aaalaniz Sure, no worries, I'll create a PR for that.
