### ISSUE TITLE
No audio input when call is initiated with bluetooth headset

### ISSUE THREAD

**Issue by AirVetLevi** [twilio/audioswitch#41]
**Describe the bug**
Participant A starts with a bluetooth headset connected to device. Participant A calls Participant B.
Participant A speaks through bluetooth headset -> Participant B can hear the audio
Participant B speaks ->  Participant A cannot hear the audio.

When Participant A opens the device selector dialog, the bluetooth headset is listed as the selected device. Participant A is able to hear audio after switching to another audio device (ie. earpiece) and then switching back to bluetooth.

**To Reproduce**
1. Have bluetooth headset connected to device
2. Initiate a call
3. No audio can be heard through bluetooth headset

**Expected behavior**
Users should be able to hear audio when they start a call with bluetooth headset.

**Actual behavior**
No audio is heard when a call is started with bluetooth headset.

**Android Device:**
 - Device: Pixel 3A
 - API Version: 29

**Version**
- Version: 0.1.5

**Bluetooth Device Used:**
-Aukey EP-T21
-SoundPEATS TrueFree2

**Comment by Alton09** [comment]
Hi @AirVetLevi . Thank you for filing this issue. We'll investigate this issue and let you know about our findings.

**Comment by aparajita-sinha** [comment]
Even I am facing exactly the same issue. I am using AudioSwitch 1.0.5. After connecting to bluetooth, the audio device goes back to earpiece on its own.

**Comment by Alton09** [comment]
@AirVetLevi  @aparajita-sinha This issue appears to be fixed as part of the latest release, 0.2.0. Can you please confirm this so we can close this issue? Thanks!

**Comment by AirVetLevi** [comment]
**Test Case:** User starts call with bluetooth headset connected. Verify that user can hear audio through bluetooth headset.
**Version:** 0.2.0
**Result:** PASSED

@Alton09 Tested this morning and the issue is fixed.

**Comment by Alton09** [comment]
Great! Glad to hear it. Thanks for validating!
