### ISSUE TITLE
Add the ability to track audio focus changes

### ISSUE THREAD

**Issue by agnusin** [twilio/audioswitch#53]
Hi! I want to track audio focus changes, that if I have incomming call on my phone (phone call or call from a messeger) I can pause my audio and video streams. Now AudioDeviceManager requests audio focus and does nothing when audio focus changes. And there isn't ability to handle the changes on client side.

Can you add the ability to add a listener that will receive audio focus changes?

**Comment by aaalaniz** [comment]
Hey @agnusin 

Great feature request. We have created a feature request in our backlog but we welcome any pull requests as well!

Thanks!

**Comment by agnusin** [comment]
Hi, @aaalaniz

I've opened the pull request https://github.com/twilio/audioswitch/pull/54

**Comment by Alton09** [comment]
Hi @agnusin . This enhancement is now part of the latest release, [0.1.4](https://github.com/twilio/audioswitch/releases/tag/0.4.0). Thanks for contributing!
