### ISSUE TITLE
Should `SystemClockWrapper` be internal? 

### ISSUE THREAD

**Issue by 4brunu** [twilio/audioswitch#67]
**Describe the bug**
When going thought the public API, I found that the class `SystemClockWrapper` is public, but from what I saw in the library, there is no reason for this class to be public, but maybe there is something that I didn't consider.

**To Reproduce**
1. Open class `SystemClockWrapper`
2. The class should (maybe???) be internal, but it's public.

**Expected behavior**
Since I see no reason for this class to be public, I was not expecting that it's in the public API.

**Actual behavior**
The class `SystemClockWrapper` is public, but maybe it's needed for something?

**Version**
- Version: 1.0.0

**Comment by Alton09** [comment]
Thanks for pointing this out @4brunu ! That class is definitely supposed to have the internal access modifier. I went ahead and took care of this as part of #68.

**Comment by 4brunu** [comment]
Thank you for the quick action 👍
