### ISSUE TITLE
The ring is not coming on the device when the Bluetooth device is connected 

### ISSUE THREAD

**Issue by Monika-Paliwal** [twilio/audioswitch#78]
Describe the bug
 I am facing one issue that is when a call comes on the Android device when it connected with Bluetooth, then the call rings on Bluetooth only, and on the mobile phone, it is not ringing.

To Reproduce

Launch the video app.
The Bluetooth is already connected with the device, when a call comes on the Android device the ring is only coming on the Bluetooth headset.

Expected behavior
When a wired headset or Bluetooth is connected it should ring on Bluetooth and the android device.

Actual behavior
After Bluetooth is Connected, the ring is only coming on the Bluetooth headset 

Android Device

Device: Samsung A30 5F
API Version: 29
Version 10

Audio switch version: 1.0.1

**Comment by Alton09** [comment]
Hi @Monika-Paliwal! Thanks for filing a separate issue for this. When you say call do you mean a mobile phone call or a VoIP call via the Android Voice SDK? If it is a mobile phone call, `AudioSwitch` has no control over the audio management of the phone call as it is being handled by the Phone system app. There may be a way to route the audio for the ringtone as the phone call comes in, but this is currently not supported in the library. Also, routing audio to two devices simultaneously is not handled by the library, and I'm not sure if it's possible (we would have to investigate).

**Comment by Monika-Paliwal** [comment]
@Alton09 I am asking about the VoIP call, not a phone call but You said that routing in two devices is not handled by this library. if you will find any solution for this issue please update.

**Comment by Alton09** [comment]
@Monika-Paliwal, thanks for providing that info. I'll mark this one as a feature request for routing audio to multiple audio devices simultaneously since this is not currently supported by the library. It is not on our current roadmap, but I will put it in our backlog to be reviewed by our team at a later time.

**Comment by Alton09** [comment]
Hi @Monika-Paliwal . After discussing this issue further with my team, we have decided not to support this request. We are following the UX behavior found in apps like the Phone system app and Google Duo where ringing audio is only routed to a single audio device. Thank you for reaching out and please feel free to open new issues regarding this library as needed.
