### ISSUE TITLE
Do audioswitch need any permission on AndroidManifest?

### ISSUE THREAD

**Issue by rocboronat** [twilio/audioswitch#79]
I'm having a problem where AudioSwitch doesn't switch from earpiece to speaker. But I feel that maybe I should add any permission on AndroidManifest.

May you clarify it on the readme? In case it doesn't need any permission, just state it. For the peace of mind of the users, hihi.

Thanks!

**Comment by Alton09** [comment]
Hi @rocboronat . There are no special permissions needed for your application as they are merged from the AudioSwitch manifest file. Thanks for the feedback! We'll be sure to add that into our README.

Regarding your issue where the audio device isn't switching properly. Can you please follow the [New Issue](https://github.com/twilio/audioswitch/issues/new?assignees=&labels=bug&template=bug_report.md&title=) template to provide us with more context around the issue? This will help us troubleshoot. Also, please include logs with the logcat filter `AS/` applied if possible. Thanks!

**Comment by Alton09** [comment]
Closing this issue @rocboronat . Please feel free to open a new issue if needed. Thanks!

**Comment by rocboronat** [comment]
Hi @Alton09! I was out of the office, hihi.

If I invest time figuring what happened there, I'll open a detailed issue. By the way, it happened on an Honor device but not in a Huawei one... weird things.

Well, thanks a lot for the support! 😄

**Comment by Alton09** [comment]
No problem, happy to help! Interesting, when you do create a new issue, please use the Bug Report template when creating a [new issue](https://github.com/twilio/audioswitch/issues/new/choose) and provide as much detail as possible to help our team troubleshoot. Thanks!
