### ISSUE TITLE
How to change default priority ? 

### ISSUE THREAD

**Issue by rulfox** [twilio/audioswitch#81]
How to change the priority from

BluetoothHeadset -> WiredHeadset -> Earpiece -> Speakerphone
to
BluetoothHeadset -> WiredHeadset -> Speakerphone -> Earpiece

**Comment by Alton09** [comment]
This is supported as of [1.1.0](https://github.com/twilio/audioswitch/releases/tag/1.1.0). Here's how to configure it for your use case:

```kotlin
val audioSwitch = AudioSwitch(application, preferredDeviceList = listOf(BluetoothHeadset::class.java, WiredHeadset::class.java, Speakerphone::class.java, Earpiece::class.java))
```

**Comment by Alton09** [comment]
Closing for now. Please feel free to reach out if additional help is needed when using this feature.
