### ISSUE TITLE
Audio Not Switching to USB-C Headphones on Certain Galaxy Devices

### ISSUE THREAD

**Issue by JaredBanyard** [twilio/audioswitch#92]
I tested the USB-C headphones on the Samsung Galaxy S9 (model:SM_G960U1 device:starqlteue). This device also has an analog audio jack. Youtube output successfully from the USB-C headphones, but using audioswitch with our twilio implementation did not.

Audioswitch detects it and shows that the audio should be going to the headset, but it still comes out of the speaker.

**Comment by Alton09** [comment]
Thanks for reaching out regarding this issue @JaredBanyard . I'll add this one to our backlog to investigate this further. Thanks!

**Comment by Qamar4P** [comment]
Same issue with S21, One Harman USB-C based handsfree is not listed in connected device

**Comment by ocarevs** [comment]
This issue has been resolved as part of https://github.com/twilio/audioswitch/pull/145
