### ISSUE TITLE
 Priority problem between WiredHeadset and Earpiece

### ISSUE THREAD

**Issue by patnh2** [twilio/audioswitch#96]
**Describe the bug**
I tested on phone with wired headset (no bluetooth headset)
I changed priority.

BluetoothHeadset -> Earpiece -> WiredHeadset -> Speakerphone

and no device selected.
I expect audio goes into Earpiece. but it goes into WiredHeadset.
how can audio go into Earpiece on the phone with wired headset?

**To Reproduce**
1. Connect wired headset (no bluetooth headset)
2. Changed priority (BluetoothHeadset -> Earpiece -> WiredHeadset -> Speakerphone)
3. No device selected
4. Audio goes into WiredHeadset

**Expected behavior**
Audio goes into Earpiece

**Actual behavior**
Audio goes into WiredHeadset

**AudioSwitch Version**
- Version: 1.1.2

**Android Device (please complete the following information):**
 - Device: samsung galaxy s8+
 - API Version: API 28

**Comment by Alton09** [comment]
Thanks for reaching out @patnh2 ! This is by design, such that whenever a WiredHeadset is plugged in it will override the earpiece. I can mark this one as a feature request and discuss with my team about adding support for this.

**Comment by patnh2** [comment]
Thanks for your reply @Alton09 !!
