### ISSUE TITLE
When should we call the activate() method?

### ISSUE THREAD

**Issue by rocboronat** [twilio/audioswitch#97]
According to the [Twilio voice quickstart](https://github.com/twilio/voice-quickstart-android), the `activate()` method should be called when the call starts, which is in the Twilio's `onConnected()` method. But if I do it and call `deactivate()` when the call ends, the audio mode goes to `ringtone` instead of `normal`. So, the user can't change the volume anymore, and the feedback he receives is like the app is actually on a call... or something weird like that. 💭 Something wrong is happening...

That's because when `activate()` is called, you save the current audio mode which is `ringtone` because the ringtone is ringing. Later, when the call ends, you restore the audio mode, passing from `in communication` to `ringtone` again, instead of `normal`.

So, am I wrongly using AudioSwitch and I should call `activate()` in another place, or is this actually a bug?

Thanks a lot for the support and also for open-sourcing this project 👍

**Comment by rocboronat** [comment]
Then, the ringtone will sound on the earpiece, right?

**Comment by afalls-twilio** [comment]
@rocboronat I see 2 issues here..
1) after deactivate was called, did it not revert to the original routing? was 'ringtone' or 'normal' the previous setting prior to calling activate?
2) If the ringtone was triggered by the same application, yes, audioswitch will route it to the earpiece if that is what is selected. If the ringtone is from another application, then I believe its up that application how its routed.
