### ISSUE TITLE
Switching to Bluetooth disconnect the user from call on Realme 5s

### ISSUE THREAD

**Issue by vismay11** [twilio/audioswitch#98]
**Describe the bug**
When the user joins the call selecting speaker or wired headphones the user is able to speak and hear everyone but as soon as the user switches to Bluetooth earphones then the user gets disconnected from the call. It is also tested on video-quickstart-android and gives the same result. I will add steps to reproduce in video-quickstart-android.

**To Reproduce**
1. Use Realme 5s and Connect to the Room by  entering Room Name
2. Once connected then switch to Bluetooth earphones
3. As soon as earphones get connected the user will be disconnected.

**Expected behavior**
Once Bluetooth earphones get connected the user should be able to hear the voice from it.

**Actual behavior**
As soon as the Bluetooth earphones get connected the user disconnects from the call.

**AudioSwitch Version**
- Version: 1.1.2

**Android Device:**
 - Device: Realme 5s
 - API Version: API 29

**Comment by vismay11** [comment]
@paynerc any update on this?

**Comment by Alton09** [comment]
Hi @vismay11 ! Sorry for the delay on this one. Our bandwidth is limited at the moment for AudioSwitch support. I'll add a ticket for this one in our backlog to have our team look into this issue when we have a chance. Thanks!

**Comment by vismay11** [comment]
Hi @Alton09, thank you!

**Comment by akardas16** [comment]
We also have same issue (happened on Samsung S20 FE). Because of that issue it is not appropriate to use this library. (After connecting Bluetooth, call is finished a few seconds later) I hope someone could fix that issue.

**Comment by afalls-twilio** [comment]
@akardas16 Can you provide more information on your statement as "After I added the library as a module, this bug has disappeared". What do you mean by "After I added the library as a module?"

**Comment by akardas16** [comment]
I have imported library to my project instead of adding it as dependency

> @akardas16 Can you provide more information on your statement as "After I added the library as a module, this bug has disappeared". What do you mean by "After I added the library as a module?"

**Comment by afalls-twilio** [comment]
Closing, issue due to customer error
